[package]
name = "br"
description = "Brut Rewriting"
version = "0.1.0"
authors = ["Pierre Marijon <pierre@marijon.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio            = "0.29"
clap           = "2.33"
bv             = "0.11.0"
enum_primitive = "0.1.1"
pcon           = { git = "https://github.com/natir/pcon" }

[profile.release]
#debug = true
lto = 'thin'
opt-level = 3
overflow-checks = false
panic = 'abort'
incremental = false